musicPlayTime: 30
choseTime: 15

reward:
  vault: false
  correct: 10
  wrong: 5

# currently not implemented!
bungeecord:
  enable: false
  lobby: Lobby

# currently not implemented!
database:
  enable: false
  host: "127.0.0.1"
  port: 3306
  database: "WhatsTheSongsName"
  username: "root"
  password: "iMsooo1SavePassword"